spring:
  application:
    name: logbat
  profiles:
    active: test
jdbc:
  async:
    timeout: 5000
    bulk-size: 3000
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
      username: admin        # H2 DB 접속 ID (사용자 지정)
      password: root
    #    url: jdbc:mysql://localhost:3306/logbat
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
      username: admin        # H2 DB 접속 ID (사용자 지정)
      password: root
    #    url: jdbc:mysql://localhost:3306/logbat
    #    username: root
    #    password:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    hikari:
    #      maximum-pool-size: 10
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소
#  datasource:
#    url: jdbc:mysql://localhost:3306/logbat
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10